---
sidebar: sidebar 
permalink: ontap-security-hardening/autonomous-ransomware-protection.html 
keywords: tr-4569, ontap hardening guide, security, ARP, fpolicy, UBA, ransomware, machine learning, volume workloads, entropy 
summary: 'La funzionalità di apprendimento automatico on-box di ONTAP rileva il ransomware in base ai workload dei volumi e all"entropia.' 
---
= Protezione autonoma dal ransomware di ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per integrare gli analytics sul comportamento degli utenti per la sicurezza del workload di storage, la protezione autonoma da ransomware di ONTAP analizza i carichi di lavoro dei volumi e l'entropia per rilevare il ransomware, crea una snapshot e informa l'amministratore quando si sospetta un attacco.

Oltre al rilevamento e alla prevenzione del ransomware mediante l'analisi comportamentale degli utenti (UBA) esterna di FPolicy con NetApp Data Infrastructure Insights Storage Workload Security e l'ecosistema di partner NetApp FPolicy, ONTAP 9.10.1 introduce una protezione autonoma dal ransomware.  La protezione autonoma contro i ransomware ONTAP utilizza una funzionalità di apprendimento automatico (ML) integrata che analizza l'attività del carico di lavoro in volume e l'entropia dei dati per rilevare automaticamente i ransomware.  Monitora le attività diverse da quelle di UBA, in modo da poter rilevare attacchi che UBA non rileva.

Per informazioni più dettagliate su questa funzionalità, vedere link:../ransomware-solutions/ransomware-overview.html["Soluzioni NetApp per il ransomware"] o link:https://docs.netapp.com/us-en/ontap/anti-ransomware/use-cases-restrictions-concept.html["Documentazione sulla protezione autonoma dal ransomware di ONTAP"^].
