---
sidebar: sidebar 
permalink: ontap-security-hardening/default-admin-accounts.html 
keywords: tr-4569, ontap hardening guide, security, RBAC, roles, restrict access, admin, diag 
summary: Limitazione delle considerazioni di accesso per gli account admin e diag 
---
= Account amministrativi predefiniti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'account admin deve essere limitato perché al ruolo di amministratore è consentito l'accesso utilizzando tutte le applicazioni. L'account diag consente l'accesso alla shell del sistema e deve essere riservato solo al supporto tecnico per eseguire le attività di risoluzione dei problemi.

Esistono due account amministrativi predefiniti: `admin` E `diag`.

Gli account orfani sono un importante vettore di sicurezza che spesso porta a vulnerabilità, inclusa l'escalation dei privilegi. Si tratta di account non necessari e inutilizzati che rimangono nell'archivio degli account utente. Si tratta principalmente di account predefiniti che non sono mai stati utilizzati o per i quali le password non sono mai state aggiornate o modificate. Per risolvere questo problema, ONTAP supporta la rimozione e la ridenominazione degli account.


NOTE: Non è possibile rimuovere o rinominare gli account predefiniti. Se un amministratore rimuove l'account, al riavvio l'account predefinito verrà ricreato. *NetApp consiglia* di bloccare tutti gli account predefiniti non necessari con il comando lock.

Sebbene gli account orfani rappresentino un problema di sicurezza significativo, *NetApp consiglia vivamente* di testare l'effetto della rimozione degli account dal repository degli account locali.



== Elenca account locali

Per elencare gli account locali, eseguire il `security login show` comando.

[listing]
----
cluster1::*> security login show -vserver cluster1

vserver: cluster1
                             Authentication             Acct   Is-Nsswitch
User/Group Name  Application Method    Role Name        Locked Group
---------------- ----------- --------- ---------------- ------ -----------
admin            console     password  admin            no     no
admin            http        password  admin            no     no
admin            ontapi      password  admin            no     no
admin            service-processor password admin       no     no
admin            ssh         password  admin            no     no
autosupport      console     password  autosupport      no     no
6 entries were displayed.

----


== Impostare la password dell'account diagnostico (diag)

Con il sistema di archiviazione viene fornito un account diagnostico denominato `diag` . È possibile utilizzare l' `diag` account per eseguire operazioni di risoluzione dei problemi in `systemshell`. L' `diag` account è l'unico account che può essere utilizzato per accedere alla shell di sistema tramite il `diag` comando privilegiato `systemshell`.


CAUTION: La shell di sistema e l'account associato `diag` sono destinati a scopi diagnostici di basso livello. Il loro accesso richiede il livello di privilegio diagnostico ed è riservato solo per essere utilizzato con la guida del supporto tecnico per eseguire le attività di risoluzione dei problemi. Né il `diag` conto né il `systemshell` sono destinati a fini amministrativi generali.

.Prima di iniziare
Prima di accedere a `systemshell`, è necessario impostare la `diag` password dell'account utilizzando il `security login password` comando . È necessario utilizzare i principi della password complessa e modificarla `diag` a intervalli regolari.

.Fasi
. Per impostare la `diag` password dell'utente dell'account:
+
[listing]
----
cluster1::> set -privilege diag

Warning: These diagnostic commands are for use by NetApp personnel only.
Do you want to continue? \{y|n}: y

cluster1::*> systemshell -node node-01
    (system node systemshell)
diag@node-01's password:

Warning: The system shell provides access to low-level
diagnostic tools that can cause irreparable damage to
the system if not used properly. Use this environment
only when directed to do so by support personnel.

node-01%
----

