---
permalink: apps-dbs.html 
sidebar: sidebar 
keywords: Databases, Applications, Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, best practices, best-practices 
summary: Questi report tecnici forniscono una panoramica delle applicazioni e dei database su ONTAP, oltre alle procedure consigliate 
---
= Report tecnici su ONTAP e applicazioni e database
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP è la base per la gestione dei dati e la protezione dei dati per molte applicazioni aziendali e tecnologie di database. I seguenti report tecnici forniscono indicazioni sulle procedure di implementazione e sulle procedure consigliate da NetApp per Microsoft SQL Server, MySQL, Oracle, PostgreSQL, SAP HANA ed Epic.



== Microsoft SQL Server

SQL Server è la base della piattaforma dati di Microsoft, che offre prestazioni mission-critical con tecnologie in memoria e informazioni più rapide su qualsiasi dato, sia in sede che nel cloud.

link:https://docs.netapp.com/us-en/ontap-apps-dbs/mssql/mssql-overview.html["Best practice per Microsoft SQL Server con ONTAP"^] Scopri come gli amministratori dello storage e dei database possono implementare con successo Microsoft SQL Server sullo storage ONTAP.


NOTE: Questa documentazione sostituisce il report tecnico precedentemente pubblicato _TR-4590: Best practice guide for Microsoft SQL Server with ONTAP._

link:https://www.netapp.com/pdf.html?item=/media/88704-tr-4976-virtualized-microsoft-sql-server-performance-on-netapp-aff-a-series-and-c-series.pdf["TR-4976: Performance virtualizzate di Microsoft SQL Server su sistemi NetApp AFF A-Series e C-Series"^]
Scopri le caratteristiche delle performance di Microsoft SQL Server utilizzando i sistemi NetApp AFF A-Series e C-Series e ottieni indicazioni su come scegliere il sistema giusto in base al carico di lavoro.

link:https://www.netapp.com/pdf.html?item=/media/12400-tr4714.pdf["TR-4714: Best practice per Microsoft SQL Server con SnapCenter"^]
Scopri ora come implementare con successo Microsoft SQL Server sullo storage ONTAP utilizzando la tecnologia SnapCenter per la protezione dei dati.



== MySQL

Questo documento descrive i requisiti di configurazione e fornisce istruzioni sull'ottimizzazione e la configurazione dello storage per l'implementazione di MySQL su ONTAP.

link:https://docs.netapp.com/us-en/ontap-apps-dbs/mysql/mysql-overview.html["Database MySQL su Best practice NetApp ONTAP"^] MySQL e le sue varianti, tra cui MariaDB e Percona, sono ampiamente utilizzati per molte applicazioni aziendali. Queste applicazioni spaziano dai siti di social networking globali ai sistemi di e-commerce di grandi dimensioni ai sistemi di hosting per PMI contenenti migliaia di istanze di database. Scopri i requisiti di configurazione e le indicazioni per l'ottimizzazione e la configurazione dello storage per l'implementazione di MySQL su ONTAP.


NOTE: Questa documentazione sostituisce il report tecnico precedentemente pubblicato _TR-4722: Database MySQL sulle Best practice NetApp ONTAP._



== Oracle

ONTAP è progettato per i database Oracle. Per decenni, ONTAP è stato ottimizzato per le esigenze uniche di i/o dei database relazionali e sono state create più funzionalità di ONTAP appositamente per soddisfare le esigenze dei database Oracle e persino su richiesta della stessa Oracle Inc.

link:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-overview.html["Database Oracle su ONTAP"^] Scopri le procedure consigliate che consentono agli amministratori dello storage e dei database di implementare con successo lo storage Oracle su ONTAP.

link:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-dp-overview.html["Data Protection di Oracle con ONTAP"^] Scopri le procedure consigliate che consentono agli amministratori dello storage e dei database di eseguire correttamente il backup, il ripristino, la replica e il disaster recovery su Oracle su storage ONTAP.

link:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-dr-overview.html["Disaster recovery di Oracle con ONTAP"^] Informazioni sulle procedure consigliate, sulle procedure di test e sulle altre considerazioni per il funzionamento dei database Oracle su un ambiente MetroCluster e SnapMirror Business Continuity.

link:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-migration-overview.html["Migrazione dei database Oracle sui sistemi di storage ONTAP"^] Scopri le considerazioni generali per la pianificazione di una strategia di migrazione, i tre diversi livelli di spostamento dei dati e consulta in dettaglio alcune delle varie procedure disponibili.


NOTE: La documentazione sopra riportata sostituisce i report tecnici precedentemente pubblicati _TR-3633: Database Oracle su ONTAP; TR-4591: Data Protection Oracle: Backup, recovery, replica; TR-4592: Oracle su MetroCluster; e TR-4534: Migrazione dei database Oracle sui sistemi di storage NetApp_

link:https://www.netapp.com/pdf.html?item=/media/85630-tr-4969.pdf["TR-4969: Performance dei database Oracle su AFF A-Series e C-Series"^]
ONTAP è una potente piattaforma per la gestione dei dati con funzionalità native che includono compressione inline, aggiornamenti hardware senza interruzioni e la possibilità di importare un LUN da uno storage array esterno. È possibile eseguire il clustering di un massimo di 24 nodi, fornendo contemporaneamente i dati attraverso i protocolli NFS (Network file System), SMB (Server message Block), iSCSI, Fibre Channel (FC) e NVMe (Nonvolatile Memory Express). Inoltre, la tecnologia Snapshot è la base per la creazione di decine di migliaia di backup online e cloni di database completamente operativi. Oltre al ricco set di funzionalità di ONTAP, esistono una vasta gamma di requisiti per gli utenti, tra cui dimensioni del database, requisiti di performance e esigenze di protezione dei dati. Scopri le performance dei database bare metal utilizzando i sistemi storage AFF, inclusi I Sistemi A-Series e C-Series, e copre sia i massimi che la differenza pratica tra le due opzioni AFF.

link:https://www.netapp.com/pdf.html?item=/media/85629-tr-4971.pdf["TR-4971: Performance del database Oracle virtualizzato su AFF A-Series e C-Series"^]
ONTAP è una potente piattaforma per la gestione dei dati con funzionalità native che includono compressione inline, aggiornamenti hardware senza interruzioni e la possibilità di importare un LUN da uno storage array esterno. È possibile eseguire il clustering di un massimo di 24 nodi, fornendo contemporaneamente i dati attraverso i protocolli NFS (Network file System), SMB (Server message Block), iSCSI, Fibre Channel (FC) e NVMe (Nonvolatile Memory Express). Inoltre, la tecnologia Snapshot è la base per la creazione di decine di migliaia di backup online e cloni di database completamente operativi. Oltre al ricco set di funzionalità di ONTAP, esistono una vasta gamma di requisiti per gli utenti, tra cui dimensioni del database, requisiti di performance e esigenze di protezione dei dati. Scopri le performance dei database virtualizzati che utilizzano i sistemi storage AFF, inclusi I Sistemi A-Series e C-Series, e copre sia i massimi che la differenza pratica tra le due opzioni AFF.

link:https://www.netapp.com/pdf.html?item=/media/9138-tr4695.pdf["TR-4695: Tiering dello storage del database con FabricPool"^]
Scopri i vantaggi e le opzioni di configurazione di FabricPool con diversi database, incluso il sistema di gestione dei database relazionali Oracle (RDBMS).

link:https://www.netapp.com/pdf.html?item=/media/40384-tr-4899.pdf["TR-4899: Failover applicativo trasparente per i database Oracle con sincronizzazione attiva SnapMirror"^] SnapMirror Active Sync (in precedenza SM-BC) e Oracle Real Application Cluster (RAC) offrono failover dell'applicazione trasparente (TAF) e continuità in caso di black-out e disastri reali. Scopri la guida alla configurazione e le procedure consigliate di uno storage array AFF con SnapMirror Active Sync come componente di storage di Oracle RAC.

link:https://www.netapp.com/pdf.html?item=/media/21901-tr-4876.pdf["TR-4876: Best practice per la soluzione e l'implementazione della multitenancy Oracle con ONTAP"^]
Scopri le procedure consigliate per il provisioning, la gestione e la protezione dei database multi-tenant Oracle utilizzando lo storage ONTAP per massimizzare i vantaggi dei database multi-tenant Oracle e delle funzionalità del software ONTAP.



== PostgreSQL

PostgreSQL viene fornito con varianti che includono PostgreSQL, PostgreSQL Plus ed EDB Postgres Advanced Server (ECAS). PostgreSQL viene in genere distribuito come database back-end per applicazioni multi-Tier. NetApp ONTAP è una scelta eccellente per l'esecuzione di database PostgreSQL per la sua affidabilità, prestazioni elevate ed efficienza di gestione dei dati.

link:https://docs.netapp.com/us-en/ontap-apps-dbs/postgres/postgres-overview.html["Database PostgreSQL sulle Best practice di ONTAP"^] PostgreSQL viene fornito con varianti che includono PostgreSQL, PostgreSQL Plus e EDB Postgres Advanced Server (EPAS). PostgreSQL viene in genere implementato come database back-end per applicazioni multi-Tier. È supportato da pacchetti middleware comuni (come PHP, Java, Python, Tcl/TK, ODBC, E JDBC) ed è stata storicamente una scelta popolare per i sistemi di gestione di database open-source. Scopri i requisiti di configurazione e le istruzioni per l'ottimizzazione e la configurazione dello storage per l'implementazione di PostgreSQL su ONTAP.


NOTE: Questa documentazione sostituisce il report tecnico precedentemente pubblicato _TR-4770: Database PostgreSQL sulle Best practice ONTAP_.



== SAP HANA

link:https://docs.netapp.com/us-en/netapp-solutions-sap/["Soluzioni per i database SAP HANA su ONTAP"^] Le Best practice per la configurazione, la gestione e l'automazione delle soluzioni SAP sono disponibili nella pagina soluzioni SAP di NetApp.



== EPIC

link:https://docs.netapp.com/us-en/ontap-apps-dbs/epic/epic-overview.html["Best practice di EPIC su ONTAP"^] Una guida per comprendere le Best practice per implementare Epic on-premise e nel cloud, rispettando al contempo gli standard di configurazione per una corretta implementazione su ONTAP.


NOTE: Questa documentazione sostituisce il report tecnico precedentemente pubblicato _TR-3923: Best practice NetApp per Epic_.
