---
sidebar: sidebar 
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, best practices, best-practices, SM-BC, SnapMirror Business Continuity 
permalink: business-continuity.html 
summary: Questi report tecnici forniscono una panoramica della business continuity in NetApp ONTAP e delle procedure consigliate 
---
= Report tecnici sulla business continuity
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp offre un'ampia gamma di soluzioni che razionalizzano la posizione in cui risiedono applicazioni e dati per migliorare le performance in modo conveniente. Data Protection, replica e disponibilità continua: La gestione dei dati di ONTAP può semplificare la data Protection con una gestione delle policy set-it-and-forget-it, offrendo business continuity con MetroCluster e SnapMirror Active Sync.

[NOTE]
====
Questi report tecnici si espandono nella link:https://docs.netapp.com/us-en/ontap/smbc/index.html["Sincronizzazione attiva di ONTAP SnapMirror"] documentazione di e link:https://docs.netapp.com/us-en/ontap-metrocluster/index.html["ONTAP MetroCluster"] del prodotto.

====


== SnapMirror Active Sync (in precedenza SM-BC)

link:https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/index.html["TR-4878: Sincronizzazione attiva SnapMirror"^] SnapMirror Active Sync è una soluzione storage continuamente disponibile con granularità a livello dell'applicazione, disponibile per ONTAP sui sistemi storage AFF o All SAN Array (ASA), per soddisfare le esigenze RPO 0 e RTO 0 delle applicazioni business più critiche.



== MetroCluster

link:https://www.netapp.com/pdf.html?item=/media/13480-tr4705.pdf["TR-4705: Architettura e progettazione della soluzione NetApp MetroCluster"^]
Questo documento descrive l'architettura di alto livello e i concetti di progettazione per le funzionalità di MetroCluster in ONTAP.

*IP MetroCluster*
link:http://www.netapp.com/us/media/tr-4689.pdf["TR-4689: IP NetApp MetroCluster"^]
MetroCluster è una soluzione di storage a disponibilità continua per ONTAP in esecuzione su sistemi FAS e AFF. MetroCluster IP è l'ultima evoluzione che utilizza un fabric di storage back-end basato su Ethernet. MetroCluster IP offre una configurazione altamente ridondante per soddisfare le esigenze delle applicazioni aziendali più critiche. MetroCluster IP è incluso in ONTAP e fornisce connettività NAS e SAN per client e server che utilizzano lo storage ONTAP.

*MetroCluster FC*
link:https://www.netapp.com/pdf.html?item=/media/13482-tr4375.pdf["TR-4375: FC NetApp MetroCluster"^]
MetroCluster offre una disponibilità continua dei dati in data center geograficamente separati per le applicazioni mission-critical. Scopri le procedure consigliate da MetroCluster FC, le decisioni di progettazione e le configurazioni supportate.
