---
settings:
  name: ONTAP technical reports
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Report tecnici ONTAP
    url: "/index.html"
  - title: Report tecnici di applicazioni e database
    url: "/apps-dbs.html"
  - title: Report tecnici sulla business continuity
    url: "/business-continuity.html"
  - title: Report tecnici sulla protezione dei dati e sul disaster recovery
    url: "/data-protection-disaster-recovery.html"
  - title: Report tecnici sui volumi FlexCache e FlexGroup
    url: "/nas-containers.html"
  - title: Report tecnici NAS
    url: "/nas.html"
  - title: Report tecnici di rete
    url: "/networking.html"
  - title: Report tecnici SAN
    url: "/san.html"
  - title: Report tecnici sulla sicurezza
    url: "/security.html"
  - title: Guide per la protezione avanzata
    url: "/security-hardening-guides.html"
  - title: Report tecnici SnapCenter
    url: "/snapcenter.html"
  - title: Rapporti tecnici di tiering
    url: "/tiering.html"
  - title: Report tecnici sulla virtualizzazione
    url: "/virtualization.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
