---
settings:
  name: ONTAP technical reports
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Report tecnici ONTAP
    url: "/index.html"
  - title: Applicazioni e database
    url: "/apps-dbs.html"
  - title: Continuità del business
    url: "/business-continuity.html"
  - title: Protezione dei dati e disaster recovery
    url: "/data-protection-disaster-recovery.html"
  - title: Volumi FlexCache e FlexGroup
    url: "/nas-containers.html"
  - title: NAS
    url: "/nas.html"
  - title: Networking
    url: "/networking.html"
  - title: SAN
    url: "/san.html"
  - title: Sicurezza
    url: "/security.html"
  - title: Guide per la protezione avanzata
    url: "/security-hardening-guides.html"
  - title: SnapCenter
    url: "/snapcenter.html"
  - title: Tiering
    url: "/tiering.html"
  - title: Virtualizzazione
    url: "/virtualization.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
