---
settings:
  name: ONTAP Technical Reports
  search: ontap-technical-reports, ontap-apps-dbs, netapp-solutions-sap
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Report tecnici di ONTAP
    url: "/index.html"
  - title: Applicazioni e database
    url: "/apps-dbs.html"
  - title: Continuità del business
    url: "/business-continuity.html"
  - title: Protezione dei dati e disaster recovery
    url: "/data-protection-disaster-recovery.html"
  - title: Volumi FlexCache e FlexGroup
    url: "/nas-containers.html"
  - title: NAS
    url: "/nas.html"
  - title: Networking
    url: "/networking.html"
  - title: SAN
    url: "/san.html"
  - title: Sicurezza
    entries:
    - title: Panoramica
      url: "/security.html"
    - section: ransomware-solutions
    - section: zero-trust
    - section: abac
  - title: Protezione avanzata
    entries:
    - title: Panoramica
      url: "/security-hardening-guides.html"
    - section: ontap-security-hardening
  - title: SnapCenter
    url: "/snapcenter.html"
  - title: Tiering
    url: "/tiering.html"
  - title: Virtualizzazione
    url: "/virtualization.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
