---
sidebar: sidebar 
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, MFA, best practices, best-practices, TR-4569 
permalink: security-hardening-guides.html 
summary: Questi report tecnici forniscono indicazioni su come rafforzare NetApp ONTAP e altri prodotti correlati a ONTAP. 
---
= Guide per la protezione avanzata
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Questi report tecnici forniscono indicazioni su come rafforzare NetApp ONTAP e altri prodotti NetApp.

[NOTE]
====
Questi report tecnici si espandono su link:https://docs.netapp.com/us-en/ontap/security-encryption/index.html["Sicurezza ONTAP e crittografia dei dati"] documentazione del prodotto.

====


== Guide per la protezione avanzata

link:https://docs.netapp.com/us-en/ontap/ontap-security-hardening/security-hardening-overview.html["TR-4569: Guida alla protezione avanzata per NetApp ONTAP"^] Scoprite come configurare NetApp ONTAP per aiutare le organizzazioni a soddisfare gli obiettivi di protezione prescritti per la riservatezza, l'integrità e la disponibilità del sistema informativo.

link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-otv-hardening-overview.html["Guida alla protezione avanzata per gli strumenti ONTAP per VMware vSphere"] Scopri come configurare gli strumenti ONTAP per VMware vSphere per aiutare le organizzazioni a soddisfare gli obiettivi di sicurezza prescritti per la riservatezza, l'integrità e la disponibilità del sistema informativo.

link:https://www.netapp.com/pdf.html?item=/media/82393-tr-4957.pdf["TR-4957: Guida alla protezione avanzata per NetApp SnapCenter"^]
Scopri come configurare il software NetApp SnapCenter per aiutare le organizzazioni a raggiungere gli obiettivi di sicurezza prescritti per la riservatezza, l'integrità e la disponibilità del sistema informativo.

link:https://www.netapp.com/pdf.html?item=/media/83591-tr-4963.pdf["TR-4963: Guida alla protezione avanzata: BlueXP Cloud Backup per le applicazioni"^]
Scopri come configurare il backup cloud di NetApp per le applicazioni per aiutare le organizzazioni a raggiungere gli obiettivi di sicurezza prescritti per la riservatezza, l'integrità e la disponibilità del sistema informativo.

link:https://netapp.com/pdf.html?item=/media/78654-tr-4943.pdf["TR-4943: Guida alla protezione avanzata per NetApp Active IQ Unified Manager"^]
Scopri come configurare NetApp Active IQ Unified Manager per aiutare le organizzazioni a raggiungere gli obiettivi di sicurezza prescritti per la riservatezza, l'integrità e la disponibilità del sistema informativo.

link:https://www.netapp.com/pdf.html?item=/media/78941-tr-4945.pdf["TR-4945: Guida al rafforzamento della protezione per l'SDK per la gestibilità NetApp"^]
Scopri come configurare l'SDK per la gestibilità NetApp (NMSDK) per aiutare le organizzazioni a raggiungere gli obiettivi di sicurezza prescritti per la riservatezza, l'integrità e la disponibilità del sistema informativo.

link:https://docs.netapp.com/us-en/ontap-metrocluster/tiebreaker/install_security.html["Guida alla protezione avanzata per host e database MetroCluster Tiebreaker"^] Scopri come configurare l'host e il database di NetApp MetroCluster Tiebreaker per aiutare le organizzazioni a soddisfare gli obiettivi di sicurezza prescritti per la riservatezza, l'integrità e la disponibilità del sistema informatico.
