---
permalink: zero-trust/zero-trust-automation-orchestration.html 
sidebar: sidebar 
keywords: tr-4829, zero trust, ontap, netapp, security, automation, orchestration, control, ansible 
summary: 'L"automazione consente alle organizzazioni di scalare le implementazioni di tipo Zero Trust oltre le procedure manuali, in modo da difendersi da attività miscibili e automatizzate' 
---
= Controlli di orchestrazione e automazione della sicurezza NetApp esterni a ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'automazione consente di eseguire un processo o una procedura con un'assistenza minima da parte dell'operatore. L'automazione consente alle organizzazioni di scalare le implementazioni di tipo Zero Trust ben oltre le procedure manuali, in modo da difendersi da attività miscibili e automatizzate.

Ansible è un tool di provisioning software open-source, gestione della configurazione e implementazione dell'applicazione. Funziona su molti sistemi Unix-like, e può configurare sia sistemi Unix-like che Microsoft Windows. Include il proprio linguaggio dichiarativo per descrivere la configurazione del sistema. Ansible è stato scritto da Michael DeHaan e acquisito da Red Hat nel 2015. Ansible si connette temporaneamente e senza agenti tramite SSH o Windows Remote Management (consentendo l'esecuzione remota di PowerShell) per eseguire i task. NetApp ha sviluppato molto di più di https://www.netapp.com/us/getting-started-with-netapp-approved-ansible-modules/index.aspx["150 moduli Ansible per il software ONTAP"^], consentendo un'ulteriore integrazione con il framework di automazione Ansible. I moduli Ansible per NetApp forniscono una serie di istruzioni su come definire lo stato desiderato e trasferirlo all'ambiente NetApp di destinazione. I moduli sono realizzati per supportare task come l'impostazione del licensing, la creazione di aggregati e di Storage Virtual Machine, la creazione di volumi e il ripristino di snapshot per citarne alcuni. Un ruolo Ansible è stato https://github.com/NetApp/ansible/tree/master/nar_ontap_security_ucd_guide["Pubblicato su GitHub"^] specifico per la NetApp DoD Unified Capabilities (UC) Deployment Guide.

Utilizzando la libreria di moduli disponibili, gli utenti possono facilmente sviluppare i playbook Ansible e personalizzarli in base alle proprie applicazioni e esigenze aziendali per automatizzare i task ordinari. Una volta scritto un playbook, puoi eseguirlo per eseguire il task specificato, risparmiando tempo e migliorando la produttività. NetApp ha creato e condiviso playbook di esempio che possono essere utilizzati direttamente o personalizzati per le tue esigenze.

Data Infrastructure Insights è uno strumento di monitoraggio dell'infrastruttura che ti offre visibilità sull'intera infrastruttura.  Con Data Infrastructure Insights puoi monitorare, risolvere i problemi e ottimizzare tutte le tue risorse, comprese le istanze del cloud pubblico e i data center privati.  Data Infrastructure Insights può ridurre il tempo medio di risoluzione del 90% e impedire che l'80% dei problemi del cloud interessino gli utenti finali.  Può inoltre ridurre in media del 33% i costi dell'infrastruttura cloud e ridurre l'esposizione alle minacce interne proteggendo i dati con informazioni fruibili.  La funzionalità Storage Workload Security di Data Infrastructure Insights consente l'analisi comportamentale degli utenti con intelligenza artificiale e apprendimento automatico per avvisare quando si verificano comportamenti anomali degli utenti dovuti a una minaccia interna.  Per ONTAP, Storage Workload Security utilizza il motore Zero Trust FPolicy.
