---
permalink: zero-trust/zero-trust-cloud-deployments.html 
sidebar: sidebar 
keywords: tr-4829, zero trust, netapp, cloud, deployments, hybrid, amazon web services, aws, microsoft azure, google cloud platform, gcp, GCNV, Google Cloud, Google Cloud NetApp Volumes 
summary: Le opzioni NetApp estendono i sistemi di gestione dei dati on-premise nel cloud ibrido con cloud provider leader con supporto per controlli di sicurezza Zero Trust 
---
= Implementazioni di cloud ibrido e zero trust
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp è l'autorità in materia di dati per il cloud ibrido. NetApp offre diverse opzioni per estendere i sistemi di gestione dei dati on-premise al cloud ibrido con Amazon Web Services (AWS), Microsoft Azure, Google Cloud e altri importanti provider cloud. Le soluzioni cloud ibride NetApp supportano gli stessi controlli di sicurezza Zero Trust disponibili con i sistemi ONTAP on-premise e lo storage software-defined ONTAP Select .

È possibile espandere facilmente la capacità nei cloud pubblici senza i tipici vincoli CAPEX utilizzando servizi file cloud-native di livello enterprise per AWS (FSxN), Google Cloud (GCNV) e Azure NetApp Files per Microsoft Azure. Ideali per carichi di lavoro ad alta intensità di dati, come analisi e DevOps, questi servizi di dati cloud combinano l'archiviazione elastica e on-demand come servizio di NetApp con la gestione dei dati ONTAP in un'offerta completamente gestita.

ONTAP consente lo spostamento dei dati tra i sistemi ONTAP locali e l'ambiente di archiviazione AWS, Google Cloud o Azure con il software di replicazione dei dati NetApp SnapMirror .
