---
sidebar: sidebar 
permalink: nfs-tls/nfs-tls-overview.html 
keywords: nfs, tls, encryption, ontap, rfc9289, in-transit, prerequisites, requirements 
summary: ONTAP 9.19.1 introduce il supporto nativo NFS su TLS, consentendo la crittografia in transito del traffico RPC NFS secondo lo standard RFC 9289, senza la necessità di Kerberos o IPsec. 
---
= Panoramica su NFS su TLS
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:toc-position: content


[role="lead"]
ONTAP 9.19.1 introduce NFS su TLS, la tanto attesa "soluzione facile" per crittografare il traffico NFS.

Prima di questa funzionalità, la crittografia del payload NFS in transito era limitata a IPsec o Kerberos. Sebbene entrambi fossero efficaci, la configurazione era complessa e le penalità sulle prestazioni potevano essere elevate. Entrambi i metodi erano soluzioni "aggiuntive", non definite in un RFC specifico per NFS. link:https://www.rfc-editor.org/rfc/rfc9289.html["RFC 9289"], intitolata "Toward Remote Procedure Call Encryption by Default", ha cambiato le cose. Ora NFSv3 e NFSv4.x possono crittografare il traffico NFS RPC in transito utilizzando TLS 1.3. Nessun bisogno di Kerberos. Nessun bisogno di IPsec.



[[prerequisites]]
== Prerequisiti

Per utilizzare ONTAP NFS su TLS, devi soddisfare i seguenti requisiti.

* ...devi eseguire ONTAP 9.19.1
+
** Al momento le personalità cloud di ONTAP non sono supportate


* ...hai la licenza NFS
* ...hai un client NFS trovato nellink:https://imt.netapp.com["Matrice di interoperabilità NetApp"]




[[what-it-doesnt-do]]
== Cosa non fa

NFS su TLS protegge il livello di trasporto: non cambia il modo in cui NFS autentica gli utenti.

*Autenticazione utente basata su certificati.* NFS su TLS *non fornisce un nuovo meccanismo di autenticazione utente*. Hai ancora bisogno di  `auth_sys` o  `krb5` per l'autenticazione utente. Puoi comunque usare  `krb5i` e  `krb5p`, ma TLS rende superflue le loro protezioni di integrità e privacy—e subirai comunque un impatto sulle prestazioni.
