---
sidebar: sidebar 
permalink: afx/afx-architecture.html 
keywords: netapp afx, architecture, storage availability zone, nvram, raid, disaggregated 
summary: 'NetApp AFX introduce significative differenze architetturali rispetto a unified ONTAP per quanto riguarda la modalità di presentazione dello storage, l"interazione dei nodi con i dischi e la gestione della capacità.' 
---
= In che modo l'architettura NetApp AFX differisce da ONTAP unificato
:allow-uri-read: 
:icons: font
:imagesdir: ../media/afx/


[role="lead"]
NetApp AFX introduce significative differenze architetturali rispetto a unified ONTAP per quanto riguarda la modalità di presentazione dello storage, l'interazione dei nodi con i dischi e la gestione della capacità.

In precedenza, abbiamo illustrato in generale come l'architettura unificata ONTAP fornisca l'archiviazione di file, oggetti e dati a blocchi tramite coppie HA connesse direttamente, ciascuna dotata di un proprio set di dischi e in grado di offrire capacità fisica tramite aggregati di dischi. In questa sezione, analizzeremo in dettaglio alcune delle principali differenze tra le architetture unificate ONTAP e NetApp AFX.



[[how-to-tell-if-a-system-is-running-netapp-afx]]
== Come capire se un sistema sta eseguendo NetApp AFX

Il modo principale per verificare se il sistema sta eseguendo NetApp AFX è eseguire il seguente comando:

[listing]
----
AFX::> node show -fields personality
node             personality
---------------- -----------
afx-01           AFX
afx-02           AFX
----
Un altro indizio è la nuova Storage Availability Zone, ma si tratta di un concetto disponibile anche per NetApp All-SAN Arrays (ASA). È possibile visualizzare la capacità tramite questo comando.

[listing]
----
AFX::> storage availability-zone show
                     Availability Zone Name: storage_availability_zone_0
                     Availability Zone UUID: 545cb59f-32e9-11f1-a2f5-d039eabdd925
                                 Total Size: 69.59TB
                              Physical Used: 837.1GB
                      Physical Used Percent: 1%
                                  Available: 68.77TB
                              Metadata Used: 837.1GB
                  Log and Recovery Metadata: 834.6GB
                              Delayed Frees: 2.50GB
 Physical User Data Without Snapshot Copies: 17.24MB
  Logical User Data Without Snapshot Copies: 17.24MB
   Efficiency Ratio Without Snapshot Copies: 1.00:1
               Space Full Threshold Percent: 98%
        Space Nearly Full Threshold Percent: 95%
----


[[architecture-topics]]
== Argomenti di architettura

* link:afx-architecture-node-disk.html["Relazioni nodo-disco"]
* link:afx-architecture-capacity-pool.html["Pool a capacità singola"]
* link:afx-architecture-nvram-ha.html["NVRAM replicata e comportamento di failover HA"]
* link:afx-architecture-independent-scale.html["Scala lineare indipendente"]
* link:afx-architecture-raid.html["Modifiche RAID"]
* link:afx-architecture-storage-efficiency.html["efficienza di storage"]
* link:afx-architecture-feature-support.html["Modifiche al supporto delle funzionalità ONTAP"]
* link:afx-architecture-flexgroup.html["Miglioramenti della gestione FlexGroup"]
* link:afx-architecture-volume-moves.html["Spostamenti di volume"]
* link:afx-architecture-cluster-scale.html["scalabilità del cluster"]
* link:afx-architecture-root-volume.html["Modifiche al volume root"]


[cols="1,1"]
|===


| link:afx-whats-new.html["Precedente"] | link:afx-architecture-node-disk.html["Successivo: Relazioni nodo-disco"] 
|===